extraction:
  cpp:
    after_prepare: 
      - python report.py 11
  cobol:
    after_prepare: 
      - python report.py 11
  csharp:
    after_prepare: 
      - python report.py 11
  java:
    after_prepare: 
      - python report.py 11
  javascript:
    after_prepare: 
      - python report.py 11
  python:
    after_prepare: 
      - python report.py 11
